### ISSUE TITLE
Does not work with Discord Flatpak

### ISSUE THREAD

**Issue by yuckdevchan** [TorchedSammy/clematis#9]
I have to use the Discord Flatpak as I'm on Steam Deck.

I get the error: 2023-03-12 18:22:21 ERROR > dial unix /run/user/1000/discord-ipc-0: connect: no such file or directory

Which I assume is because it's looking for the discord binary if installed through a package manager.

**Comment by TorchedSammy** [comment]
follow the steps here https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc) since this is actually a flatpak problem (or was)?

I'm taking a break from programming my programs so I'll look at this in maybe a weeks or a few days

**Comment by yuckdevchan** [comment]
Thanks, I run the command: `ln -sf $XDG_RUNTIME_DIR/{app/com.discordapp.Discord,}/discord-ipc-0`. And it worked perfectly after that. Nice program btw.
